Raw Format .txt rendering fix Ref: Issue #81
jsonresume/jsonresume.org pull request #82
Opened 2024-05-06 18:33 UTC by tylermneher

Should fix the issue I raised [The Registry's .txt Raw Format Incorrectly Renders Location, Phone, and Email Information #81](https://github.com/jsonresume/jsonresume.org/issues/81).

2024-05-07 08:28 UTC, levino commented
Hey @tylermneher, thank you for your contribution and for finding the bug. Unfortunately we will have to wait for the clean up PR #83 to be merged first and then we can proceed here. Please be patient for a bit.

2024-05-07 08:29 UTC, levino requested changes
Please remove all dead code.

2024-05-07 08:29 UTC, levino commented on apps/registry/pages/api/formatters/text.js
> +// Pittsburgh, PA 15201
```suggestion
```

2024-05-07 08:29 UTC, levino commented on apps/registry/pages/api/formatters/text.js
> +// (555) 555-5555
```suggestion
```

2024-05-07 08:29 UTC, levino commented on apps/registry/pages/api/formatters/text.js
> +// example@example.com
```suggestion
```

2024-05-08 08:20 UTC, thomasdavis commented
@tylermneher not overly bothered with the comments being in there but you might as well remove them and then we can merge.

great work nontheless

2024-05-08 08:37 UTC, levino approved these changes

2024-05-08 08:37 UTC, merged